"""add google oauth support to calendar sources

Revision ID: 4a229060d36b
Revises: 0d1445e03b3d
Create Date: 2025-12-25 19:47:38.314939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a229060d36b'
down_revision: Union[str, None] = '0d1445e03b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE sourcetype AS ENUM ('ical', 'google_oauth')")

    op.add_column('calendar_sources', sa.Column('source_type', sa.Enum('ical', 'google_oauth', name='sourcetype'), nullable=False))
    op.add_column('calendar_sources', sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
    op.add_column('calendar_sources', sa.Column('oauth_access_token_encrypted', sa.Text(), nullable=True))
    op.add_column('calendar_sources', sa.Column('oauth_refresh_token_encrypted', sa.Text(), nullable=True))
    op.add_column('calendar_sources', sa.Column('oauth_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calendar_sources', sa.Column('oauth_scopes', sa.Text(), nullable=True))
    op.alter_column('calendar_sources', 'ical_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_sources', 'ical_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('calendar_sources', 'oauth_scopes')
    op.drop_column('calendar_sources', 'oauth_token_expires_at')
    op.drop_column('calendar_sources', 'oauth_refresh_token_encrypted')
    op.drop_column('calendar_sources', 'oauth_access_token_encrypted')
    op.drop_column('calendar_sources', 'google_calendar_id')
    op.drop_column('calendar_sources', 'source_type')

    # Drop the enum type after dropping the column
    op.execute("DROP TYPE sourcetype")
    # ### end Alembic commands ###
